### ISSUE TITLE
running the unit tests

### ISSUE THREAD

**Issue by james-wilson** [amplience/amplience-sdk-client#7]
Hi,

I've been trying to run the unit tests but am having no joy. We would likely be using a different version of jQuery and jQuery UI than that mentioned in the set up and wanted to check if we'd still pass the test.

So far I haven't been able to get them to run at all. Been doing the following;
- git clone https://github.com/amplience/amplience-sdk-client.git
- cd amplience-sdk-client/
- npm install  
- npm test  

Would it be possible to update the README with instructions on how to run the tests?

Thanks,
James

**Comment by stephen-james** [comment]
Hi James,

You're quite right, the `npm test` script needs to be wired up, in the mean time, if you want to test manually, I can recommend the following steps...
- `git clone https://github.com/amplience/amplience-sdk-client.git`
- `cd amplience-sdk-client/`
- `npm install`
- `bower up`  <--- please note that you may want to edit the versions of jquery and jquery ui in the `bower.json` file to match the versions you wish to test, before running this command, or if you want to change them later, you'll have to rerun `bower up`
- `grunt karma:unit`

This will run the [Karma test runner](http://karma-runner.github.io/0.12/index.html) against the following browsers - Chrome, Firefox & IE.

If you wish to run it only against Chrome for example, please adjust the Karma `browser` settings [in the Gruntfile](https://github.com/amplience/amplience-sdk-client/blob/master/Gruntfile.js#L142)

Hope that helps!
Stephen

**Comment by james-wilson** [comment]
Thanks Stephen,

Have got the test running (and passing!) now.

In the end had to run <code>grunt tests</code> instead of <code>grunt karma:unit</code>, looks like the tests rely on the SDK being built out.

Thanks again,
James

**Comment by stephen-james** [comment]
commit cecd8d93ef76865990baca23f5b1315050863c04 currently staged in release branch v0.1.2 should help address this issue.

`npm install` now performs `bower up` as a postinstall
from there running `npm test` will run the unit tests for Chrome only

this issue will be closed when v0.1.2 is released

**Comment by stephen-james** [comment]
Thanks for raising this issue!  Changes to assist with this problem have been released with v0.1.2 , so I'm closing this issue, please comment back if any further help is needed or you have any further suggestions.
